# Dockerfile for Grafana
FROM grafana/grafana:latest

# Expose Grafana's default port
EXPOSE 3000

# Copy provisioning files
COPY provisioning /etc/grafana/provisioning

# Copy dashboards
COPY provisioning/dashboards /var/lib/grafana/dashboards

