scrape_configs:
  - job_name: "beacon-deposits"
    scrape_interval: 10s
    static_configs:
      - targets: ["exporter:8080"]
        labels:
          network: "ethereum"
          chain: "mainnet"
          currency: "ETH"
