{
 "title": "Ethereum Mainnet Deposit Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latest Deposit Block Number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_deposit_block_number{job=\"beacon-deposits\", network=\"ethereum\", chain=\"mainnet\"}",
     "legendFormat": "Latest Block Number"
    }
   ]
  },
  {
   "title": "Latest Deposit Fee",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "eth wei" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_deposit_fee{job=\"beacon-deposits\", network=\"ethereum\", chain=\"mainnet\"}",
     "legendFormat": "Latest Deposit Fee"
    }
   ]
  },
  {
   "title": "Latest Deposit Timestamp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "latest_deposit_timestamp{job=\"beacon-deposits\", network=\"ethereum\", chain=\"mainnet\"}",
     "legendFormat": "Latest Deposit Timestamp"
    }
   ]
  }
 ]
}